// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: PBBattle.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace PBBattle
{

    [global::ProtoBuf.ProtoContract()]
    public partial class UdpReadyBattle : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uid", IsRequired = true)]
        public int Uid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"roomid", IsRequired = true)]
        public int Roomid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UdpReadyBattleResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public bool Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleUserInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uid", IsRequired = true)]
        public int Uid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int roleID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TcpEnterBattle : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int randSeed { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"battleUserInfo")]
        public global::System.Collections.Generic.List<BattleUserInfo> battleUserInfoes { get; } = new global::System.Collections.Generic.List<BattleUserInfo>();

    }
    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerOperation : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uid", IsRequired = true)]
        public int Uid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"move", IsRequired = true)]
        public int Move { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int operationID
        {
            get => __pbn__operationID.GetValueOrDefault();
            set => __pbn__operationID = value;
        }
        public bool ShouldSerializeoperationID() => __pbn__operationID != null;
        public void ResetoperationID() => __pbn__operationID = null;
        private int? __pbn__operationID;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(RightOpType.Noop)]
        public RightOpType rightOperation
        {
            get => __pbn__rightOperation ?? RightOpType.Noop;
            set => __pbn__rightOperation = value;
        }
        public bool ShouldSerializerightOperation() => __pbn__rightOperation != null;
        public void ResetrightOperation() => __pbn__rightOperation = null;
        private RightOpType? __pbn__rightOperation;

        [global::ProtoBuf.ProtoMember(5)]
        public int operationValue1
        {
            get => __pbn__operationValue1.GetValueOrDefault();
            set => __pbn__operationValue1 = value;
        }
        public bool ShouldSerializeoperationValue1() => __pbn__operationValue1 != null;
        public void ResetoperationValue1() => __pbn__operationValue1 = null;
        private int? __pbn__operationValue1;

        [global::ProtoBuf.ProtoMember(6)]
        public int operationValue2
        {
            get => __pbn__operationValue2.GetValueOrDefault();
            set => __pbn__operationValue2 = value;
        }
        public bool ShouldSerializeoperationValue2() => __pbn__operationValue2 != null;
        public void ResetoperationValue2() => __pbn__operationValue2 = null;
        private int? __pbn__operationValue2;

    }
    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class UdpPlayerOperations : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"roomid", IsRequired = true)]
        public int Roomid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int frameNum { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"operation", IsRequired = true)]
        public PlayerOperation Operation { get; set; }

    }
    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class AllPlayerOperation : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"operations")]
        public global::System.Collections.Generic.List<PlayerOperation> Operations { get; } = new global::System.Collections.Generic.List<PlayerOperation>();

    }
    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class UdpAllPlayerOperations : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int frameID { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"operations", IsRequired = true)]
        public AllPlayerOperation Operations { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum RightOpType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"noop")]
        Noop = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"rop1")]
        Rop1 = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"rop2")]
        Rop2 = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"rop3")]
        Rop3 = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"rop4")]
        Rop4 = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"rop5")]
        Rop5 = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"rop6")]
        Rop6 = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"rop7")]
        Rop7 = 7,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
